version: '3.7'
services:
  test-neo4j:
    container_name: test-neo4j
    image: neo4j:4.4.17
    environment:
      NEO4J_AUTH: neo4j/theneo4jpassword
      NEO4JLABS_PLUGINS: '["apoc"]'
    healthcheck:
      test: [ "CMD", "cypher-shell", "-u", "neo4j", "-p", "theneo4jpassword", "-d", "neo4j", 'CALL db.ping()' ]
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 20s
    ports:
      - 7475:7474
      - 7688:7687

  test-rabbit-mq:
    container_name: test-rabbit-mq
    image: rabbitmq:3.12.0-management
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 20s
    ports:
      - 5673:5672
      - 15673:15672