name: Linting test for icij-worker

on:
  pull_request:
    paths:
      - 'icij-worker/**.py'
  push:
    paths:
      - 'icij-worker/**.py'

# TODO: leverage some caching here
jobs:
  linting-test-icij-worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pylint
        with:
          path: icij-worker
