name: Linting test for icij-common

on:
  push:
    branches: ['main']
  pull_request:
    paths:
      - 'icij-common/**.py'
      - '.github/workflows/tests-common.yml'

jobs:
  linting-test-icij-common:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pylint
        with:
          path: icij-common
