name: Publish icij-common

on:
  push:
    tags:
      - icij-common-*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create GH release
        run: gh release create "$tag" --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}

  publish-icij-common:
    needs: [create-release]
    runs-on: ubuntu-latest
    environment:
      name: pypi-icij-common
      url: https://pypi.org/project/icij-common/
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.7"
          python-version: "3.10"
      - name: Build and publish on PyPi
        run: |
          cd icij-common
          uv build
          uv publish --trusted-publishing always
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
