name: Publish icij-worker

on:
  push:
    tags:
      - icij-worker-*

jobs:
  publish-icij-worker:
    runs-on: ubuntu-latest
    environment:
      name: pypi-icij-worker
      url: https://pypi.org/project/icij-worker/
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.7"
          python-version: "3.10"
      - name: Build and publish on PyPi
        run: |
          cd icij-worker
          uv build
          uv publish --trusted-publishing always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
